name: ❓ Question
description: Ask a question about using this Ansible role
title: '[QUESTION] '
labels: ['question', 'needs-triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your question! Please fill out the form below to help us provide the best answer.

  - type: textarea
    id: question
    attributes:
      label: ❓ Question
      description: A clear and concise description of what you want to know.
      placeholder: What is your question?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 🌍 Context
      description: |
        Please provide context about what you're trying to achieve:
        - What is your use case?
        - What have you already tried?
        - What documentation have you consulted?
      placeholder: Provide context for your question...
    validations:
      required: true

  - type: textarea
    id: current-configuration
    attributes:
      label: 🔧 Current Configuration
      description: If relevant, show your current role configuration (remove sensitive information)
      placeholder: |
        ```yaml
        # Your current configuration
        ```
      render: yaml

  - type: checkboxes
    id: research-done
    attributes:
      label: 🔍 Research Done
      description: What have you already tried to find the answer?
      options:
        - label: Checked the README
        - label: Searched existing issues
        - label: Consulted Ansible documentation
        - label: Asked in community forums
        - label: Checked role defaults and variables

  - type: textarea
    id: additional-context
    attributes:
      label: 📎 Additional Context
      description: Add any other context about your question here.
      placeholder: Additional information...
